language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"
  - "iojs-v1.0"
sudo: false
git:
  depth: 10
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d7d5bbc342402e8a9d3
    on_success: always
    on_failure: always
script: "npm run-script test-ci"
after_script: "cat ./coverage/lcov.info | coveralls"