language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"
  - "iojs-v1.0"
sudo: false
git:
  depth: 10
branches:
  only:
    - master
script: "npm run-script test-ci"
after_script: "cat ./coverage/lcov.info | coveralls"